In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv(r'anime.csv')
df.head(5)

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [16]:
df.loc[2]

Rank                                                     3
Title    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
Score                                                 9.06
Name: 2, dtype: object

In [17]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [18]:
def ep(txt):
    data = ''
    inside = False
    for i in txt:
        if i=='(':
            inside = True
            continue
        if i == ')':
            break

        if inside:
            data+=i
    return data

In [19]:
df['Episodes']=df['Title'].apply(ep)
df['Episodes']=df['Episodes'].str.replace(' eps','')
df['Episodes']=df['Episodes'].astype(int)
df.loc[0]['Episodes']

np.int64(64)

In [20]:
df[:5]

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

Extract time period

In [21]:
df.loc[1]['Title']

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [22]:
def time_period(txt):
    inside = False
    data = ''
    for i in range(len(txt)):
        if txt[i]==')':
            for j in range(i+1,i+20):
                data+=txt[j]
            return data

# time_period('Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members')

In [23]:
df['Time Period']=df['Title'].apply(time_period)
df[:5]

,Rank,Title,Score,Episodes,Time Period
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

Calculate Total Month

In [24]:


def total_months(period):
    start, end = period.split(' - ')

    start = pd.to_datetime(start, format='%b %Y')
    end = pd.to_datetime(end, format='%b %Y')

    return (end.year - start.year) * 12 + (end.month - start.month)

total_months('Apr 2009 - Jul 2010')

15

In [25]:
df['Months'] = df['Time Period'].apply(total_months)
df[:5]

,Rank,Title,Score,Episodes,Time Period,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [26]:
max_score = df['Score'].max()
mask = df['Score'] == max_score
df[mask]

,Rank,Title,Score,Episodes,Time Period,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,15