In [76]:
import numpy as np
import pandas as pd

# Creating Series

In [77]:
labels = ['a', 'b', 'c']
li = [10,20,30]
arr = np.array([10,20,30])
dic = {"a":10,2:20,3:30}

In [78]:
pd.Series(li,index=labels)

a    10
b    20
c    30
dtype: int64

In [79]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [80]:
pd.Series(dic)

a    10
2    20
3    30
dtype: int64

# Data Frame

In [81]:

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [82]:

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
pd.DataFrame(data_list)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [83]:
col = ["Name", "age", "city", "salary"]
idx = [1,2,3,4]
pd.DataFrame(data_list,index=idx, columns=col)

    Name  age      city  salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

# Selection and Indexing of Columns

In [84]:
dt = pd.DataFrame(data_list,index=idx, columns=col)
dt

    Name  age      city  salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

In [85]:
dt['Name']

1     John
2     Anna
3    Peter
4    Linda
Name: Name, dtype: str

In [86]:
dt[['Name','city']]

    Name      city
1   John  New York
2   Anna     Paris
3  Peter    Berlin
4  Linda    London

In [87]:
dt['id'] = [101,102,103,104] # add column
dt

    Name  age      city  salary   id
1   John   28  New York   65000  101
2   Anna   34     Paris   70000  102
3  Peter   29    Berlin   62000  103
4  Linda   42    London   85000  104

In [88]:
dt.drop('id',axis=1) # axis=0 row , axis=1 column

    Name  age      city  salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

In [89]:
dt.drop(3,axis=0)

    Name  age      city  salary   id
1   John   28  New York   65000  101
2   Anna   34     Paris   70000  102
4  Linda   42    London   85000  104

In [90]:
dt.drop('id',axis=1, inplace=True) # delete from memory
dt

    Name  age      city  salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

In [91]:
dt.drop(['Name','city'],axis=1, inplace=True)
dt

   age  salary
1   28   65000
2   34   70000
3   29   62000
4   42   85000

# Selection and Indexing of Rows

In [92]:
dt = pd.DataFrame(data_list,index=idx, columns=col)
dt

    Name  age      city  salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

In [93]:
dt.loc[1]

Name          John
age             28
city      New York
salary       65000
Name: 1, dtype: object

In [94]:
dt.loc[[1,2]]

   Name  age      city  salary
1  John   28  New York   65000
2  Anna   34     Paris   70000

In [95]:
dt.iloc[1]

Name       Anna
age          34
city      Paris
salary    70000
Name: 2, dtype: object

# Selecting Subsets of Rows and Columns

In [96]:
dt

    Name  age      city  salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

In [97]:
dt.loc[1]["Name"]

'John'

In [98]:
dt.loc[[1,2]]   [["Name",'city']]

   Name      city
1  John  New York
2  Anna     Paris

# Conditional Selection

In [99]:
dt

    Name  age      city  salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

In [100]:
# age above 30
dt['age']>30

1    False
2     True
3    False
4     True
Name: age, dtype: bool

In [101]:
dt[dt["age"]>30]

    Name  age    city  salary
2   Anna   34   Paris   70000
4  Linda   42  London   85000

In [102]:
# age > 30 and city Paris
x = (dt['city'] == "Paris") | (dt['city'] == "London") & (dt['age'] > 30)
x

1    False
2     True
3    False
4     True
dtype: bool

In [103]:
dt[x]

    Name  age    city  salary
2   Anna   34   Paris   70000
4  Linda   42  London   85000

# Missing Data

In [104]:

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [105]:
df.isna() #checks null value

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [106]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [107]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

# Removing Missing Data

In [108]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [109]:
df.dropna()  # remove all rows which includes Null values

     A  B    C    D
0  1.0  1  1.0  1.0

In [110]:
df.dropna(thresh=3) # 3 non-null values thakbe

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

# Filling null/missing data

In [111]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [112]:
df.fillna(0)  # replace null with 0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [113]:
val = {'A':'xxx','B':1000,'C':2000, 'D':'xyz'}
df.fillna(val)

     A  B       C    D
0  1.0  1     1.0  1.0
1  2.0  2     2.0  xyz
2  xxx  3     3.0  xyz
3  4.0  4  2000.0  xyz
4  5.0  5  2000.0  5.0

# Merging Joining Concatination

In [114]:

em = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})


sal = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [115]:
em

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [116]:
sal

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [117]:
pd.merge(em,sal,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [118]:
pd.merge(em,sal,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [119]:
pd.merge(em,sal,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [120]:
pd.merge(em,sal,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

# Concatination

In [121]:

df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [122]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [123]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [124]:
pd.concat([df1,df2],axis=0)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [125]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

# Joining

In [126]:

df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])


df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [127]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [128]:
df2

   score
2     85
3     90
4     75

In [129]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [130]:
df1.join(df2,how='inner')

      name  score
2      Bob     85
3  Charlie     90

In [131]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

# Group By Aggregation

In [132]:

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [133]:
#Grp by category and calculate sum of sales
cat = df.groupby('Category')
for i,j in cat:
  print(f"{i}  {j}")

A    Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B    Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [134]:
sum = df.groupby('Category')['Sales'].sum()
sum

Category
A    570
B    930
Name: Sales, dtype: int64

In [135]:
sum = df.groupby('Store')['Sales'].sum()
sum

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [136]:
sum = df.groupby(['Category','Store'])['Sales'].sum()
sum

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [137]:
# Aggregation: mean median mode std max min count
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [138]:
df['Sales'].agg(['mean','median','max','min','count','sum'])

mean       187.5
median     190.0
max        300.0
min        100.0
count        8.0
sum       1500.0
Name: Sales, dtype: float64

# Pivot Table

In [139]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    954     16   John  January      Q1
1  2023-01-02       B   West    465     31   Mary  January      Q1
2  2023-01-03       C  North    912     39    Bob  January      Q1
3  2023-01-04       D  South    171     75  Alice  January      Q1
4  2023-01-05       A   East    913     63   John  January      Q1
5  2023-01-06       B   West    837     35   Mary  January      Q1
6  2023-01-07       C  North    579     70    Bob  January      Q1
7  2023-01-08       D  South    410     30  Alice  January      Q1
8  2023-01-09       A   East    782     61   John  January      Q1
9  2023-01-10       B   West    773     47   Mary  January      Q1
10 2023-01-11       C  North    164     58    Bob  January      Q1
11 2023-01-12       D  South    855     13  Alice  January      Q1
12 2023-01-13       A   East    723     86   John  January      Q1
13 2023-01-14       B   West    469     88   Mary  January      Q1
14 2023-01-15       C  North    825     90    Bob  January      Q1
15 2023-01-16       D  South    362     34  Alice  January      Q1
16 2023-01-17       A   East    781     98   John  January      Q1
17 2023-01-18       B   West    797     25   Mary  January      Q1
18 2023-01-19       C  North    244     63    Bob  January      Q1
19 2023-01-20       D  South    808     43  Alice  January      Q1

In [140]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='median')

Product      A      B      C      D
Region
East     782.0    NaN    NaN    NaN
North      NaN    NaN  579.0    NaN
South      NaN    NaN    NaN  410.0
West       NaN  773.0    NaN    NaN

In [141]:
pd.pivot_table(df, values=['Sales','Units'], index='Region', columns='Product', aggfunc='median')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     782.0    NaN    NaN    NaN  63.0   NaN   NaN   NaN
North      NaN    NaN  579.0    NaN   NaN   NaN  63.0   NaN
South      NaN    NaN    NaN  410.0   NaN   NaN   NaN  34.0
West       NaN  773.0    NaN    NaN   NaN  35.0   NaN   NaN

# Cross Tabs

In [142]:
# gives counts
pd.crosstab(index=df['Region'], columns=df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# Operations

In [143]:

df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [144]:
df1.shape

(5, 3)

In [145]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [146]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [147]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [148]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [149]:
def sq(x):
  return x**2

In [150]:
df1['B^2'] = df1['B'].apply(sq)
df1

   A   B    C   B^2
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500